# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven auto-build

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'

jobs:
  build:
    name: "Auto-build PR"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Get SHA of latest commit
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build with Maven
        run: mvn versions:set -DnewVersion=auto-build-${{ steps.vars.outputs.sha_short }} && mvn clean compile assembly:single --file pom.xml

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Auto-build Pull Request ${{ github.event.number }}"
          files: |
            LICENSE.md
            target/*.jar
